### ISSUE TITLE
Only enqueue script/css when shortcode is used

### ISSUE THREAD

**Issue by opicron** [passionsplay/wp-asciinema#2]
Can you add the following do the add_shortcode:

wp_enqueue_script( 'asciinema');
wp_enqueue_style( 'asciinema');

And change the enqueues to registers:

wp_register_script( 'asciinema', WP_Asciinema_Plugin::get_plugin_folder( 'url' ) . 'assets/vendor/asciinema-player.js', array(), 'v2.6.1', true );
wp_register_style( 'asciinema', WP_Asciinema_Plugin::get_plugin_folder( 'url' ) . 'assets/vendor/asciinema-player.css', array(), 'v2.6.1' );

This way the script only adds when the shortcode is used.

Methods and examples here:
https://wordpress.stackexchange.com/questions/165754/enqueue-scripts-styles-when-shortcode-is-present

**Comment by bgturner** [comment]
Fixed by @javierruizjimenez pull request: #5

**Comment by opicron** [comment]
Thanks!
